// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project/project.proto

#ifndef PROTOBUF_project_2fproject_2eproto__INCLUDED
#define PROTOBUF_project_2fproject_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ide {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_project_2fproject_2eproto();
void protobuf_AssignDesc_project_2fproject_2eproto();
void protobuf_ShutdownFile_project_2fproject_2eproto();

class Project;

// ===================================================================

class Project : public ::google::protobuf::Message {
 public:
  Project();
  virtual ~Project();

  Project(const Project& from);

  inline Project& operator=(const Project& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Project& default_instance();

  void Swap(Project* other);

  // implements Message ----------------------------------------------

  Project* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Project& from);
  void MergeFrom(const Project& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string root = 2;
  inline bool has_root() const;
  inline void clear_root();
  static const int kRootFieldNumber = 2;
  inline const ::std::string& root() const;
  inline void set_root(const ::std::string& value);
  inline void set_root(const char* value);
  inline void set_root(const char* value, size_t size);
  inline ::std::string* mutable_root();
  inline ::std::string* release_root();
  inline void set_allocated_root(::std::string* root);

  // repeated string file = 3;
  inline int file_size() const;
  inline void clear_file();
  static const int kFileFieldNumber = 3;
  inline const ::std::string& file(int index) const;
  inline ::std::string* mutable_file(int index);
  inline void set_file(int index, const ::std::string& value);
  inline void set_file(int index, const char* value);
  inline void set_file(int index, const char* value, size_t size);
  inline ::std::string* add_file();
  inline void add_file(const ::std::string& value);
  inline void add_file(const char* value);
  inline void add_file(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& file() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_file();

  // @@protoc_insertion_point(class_scope:ide.proto.Project)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_root();
  inline void clear_has_root();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::std::string* root_;
  ::google::protobuf::RepeatedPtrField< ::std::string> file_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_project_2fproject_2eproto();
  friend void protobuf_AssignDesc_project_2fproject_2eproto();
  friend void protobuf_ShutdownFile_project_2fproject_2eproto();

  void InitAsDefaultInstance();
  static Project* default_instance_;
};
// ===================================================================


// ===================================================================

// Project

// required string name = 1;
inline bool Project::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Project::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Project::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Project::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Project::name() const {
  return *name_;
}
inline void Project::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Project::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Project::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Project::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Project::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Project::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string root = 2;
inline bool Project::has_root() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Project::set_has_root() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Project::clear_has_root() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Project::clear_root() {
  if (root_ != &::google::protobuf::internal::kEmptyString) {
    root_->clear();
  }
  clear_has_root();
}
inline const ::std::string& Project::root() const {
  return *root_;
}
inline void Project::set_root(const ::std::string& value) {
  set_has_root();
  if (root_ == &::google::protobuf::internal::kEmptyString) {
    root_ = new ::std::string;
  }
  root_->assign(value);
}
inline void Project::set_root(const char* value) {
  set_has_root();
  if (root_ == &::google::protobuf::internal::kEmptyString) {
    root_ = new ::std::string;
  }
  root_->assign(value);
}
inline void Project::set_root(const char* value, size_t size) {
  set_has_root();
  if (root_ == &::google::protobuf::internal::kEmptyString) {
    root_ = new ::std::string;
  }
  root_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Project::mutable_root() {
  set_has_root();
  if (root_ == &::google::protobuf::internal::kEmptyString) {
    root_ = new ::std::string;
  }
  return root_;
}
inline ::std::string* Project::release_root() {
  clear_has_root();
  if (root_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = root_;
    root_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Project::set_allocated_root(::std::string* root) {
  if (root_ != &::google::protobuf::internal::kEmptyString) {
    delete root_;
  }
  if (root) {
    set_has_root();
    root_ = root;
  } else {
    clear_has_root();
    root_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated string file = 3;
inline int Project::file_size() const {
  return file_.size();
}
inline void Project::clear_file() {
  file_.Clear();
}
inline const ::std::string& Project::file(int index) const {
  return file_.Get(index);
}
inline ::std::string* Project::mutable_file(int index) {
  return file_.Mutable(index);
}
inline void Project::set_file(int index, const ::std::string& value) {
  file_.Mutable(index)->assign(value);
}
inline void Project::set_file(int index, const char* value) {
  file_.Mutable(index)->assign(value);
}
inline void Project::set_file(int index, const char* value, size_t size) {
  file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Project::add_file() {
  return file_.Add();
}
inline void Project::add_file(const ::std::string& value) {
  file_.Add()->assign(value);
}
inline void Project::add_file(const char* value) {
  file_.Add()->assign(value);
}
inline void Project::add_file(const char* value, size_t size) {
  file_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Project::file() const {
  return file_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Project::mutable_file() {
  return &file_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace ide

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_project_2fproject_2eproto__INCLUDED
