// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project/project.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "project/project.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ide {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* Project_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Project_reflection_ = NULL;
const ::google::protobuf::Descriptor* Project_Variant_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Project_Variant_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_project_2fproject_2eproto() {
  protobuf_AddDesc_project_2fproject_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "project/project.proto");
  GOOGLE_CHECK(file != NULL);
  Project_descriptor_ = file->message_type(0);
  static const int Project_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project, root_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project, file_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project, variant_),
  };
  Project_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Project_descriptor_,
      Project::default_instance_,
      Project_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Project));
  Project_Variant_descriptor_ = Project_descriptor_->nested_type(0);
  static const int Project_Variant_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project_Variant, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project_Variant, build_dir_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project_Variant, target_),
  };
  Project_Variant_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Project_Variant_descriptor_,
      Project_Variant::default_instance_,
      Project_Variant_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project_Variant, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Project_Variant, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Project_Variant));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_project_2fproject_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Project_descriptor_, &Project::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Project_Variant_descriptor_, &Project_Variant::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_project_2fproject_2eproto() {
  delete Project::default_instance_;
  delete Project_reflection_;
  delete Project::_default_root_;
  delete Project_Variant::default_instance_;
  delete Project_Variant_reflection_;
  delete Project_Variant::_default_target_;
}

void protobuf_AddDesc_project_2fproject_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025project/project.proto\022\tide.proto\"\244\001\n\007P"
    "roject\022\014\n\004name\030\001 \002(\t\022\017\n\004root\030\002 \001(\t:\001.\022\014\n"
    "\004file\030\003 \003(\t\022+\n\007variant\030\004 \003(\0132\032.ide.proto"
    ".Project.Variant\032\?\n\007Variant\022\014\n\004name\030\001 \002("
    "\t\022\021\n\tbuild_dir\030\002 \002(\t\022\023\n\006target\030\003 \001(\t:\003al"
    "l", 201);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "project/project.proto", &protobuf_RegisterTypes);
  Project::_default_root_ =
      new ::std::string(".", 1);
  Project::default_instance_ = new Project();
  Project_Variant::_default_target_ =
      new ::std::string("all", 3);
  Project_Variant::default_instance_ = new Project_Variant();
  Project::default_instance_->InitAsDefaultInstance();
  Project_Variant::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_project_2fproject_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_project_2fproject_2eproto {
  StaticDescriptorInitializer_project_2fproject_2eproto() {
    protobuf_AddDesc_project_2fproject_2eproto();
  }
} static_descriptor_initializer_project_2fproject_2eproto_;

// ===================================================================

::std::string* Project_Variant::_default_target_ = NULL;
#ifndef _MSC_VER
const int Project_Variant::kNameFieldNumber;
const int Project_Variant::kBuildDirFieldNumber;
const int Project_Variant::kTargetFieldNumber;
#endif  // !_MSC_VER

Project_Variant::Project_Variant()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ide.proto.Project.Variant)
}

void Project_Variant::InitAsDefaultInstance() {
}

Project_Variant::Project_Variant(const Project_Variant& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ide.proto.Project.Variant)
}

void Project_Variant::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  build_dir_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_ = const_cast< ::std::string*>(_default_target_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Project_Variant::~Project_Variant() {
  // @@protoc_insertion_point(destructor:ide.proto.Project.Variant)
  SharedDtor();
}

void Project_Variant::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (build_dir_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete build_dir_;
  }
  if (target_ != _default_target_) {
    delete target_;
  }
  if (this != default_instance_) {
  }
}

void Project_Variant::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Project_Variant::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Project_Variant_descriptor_;
}

const Project_Variant& Project_Variant::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_project_2fproject_2eproto();
  return *default_instance_;
}

Project_Variant* Project_Variant::default_instance_ = NULL;

Project_Variant* Project_Variant::New() const {
  return new Project_Variant;
}

void Project_Variant::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    if (has_build_dir()) {
      if (build_dir_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        build_dir_->clear();
      }
    }
    if (has_target()) {
      if (target_ != _default_target_) {
        target_->assign(*_default_target_);
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Project_Variant::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ide.proto.Project.Variant)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_build_dir;
        break;
      }

      // required string build_dir = 2;
      case 2: {
        if (tag == 18) {
         parse_build_dir:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_build_dir()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->build_dir().data(), this->build_dir().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "build_dir");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_target;
        break;
      }

      // optional string target = 3 [default = "all"];
      case 3: {
        if (tag == 26) {
         parse_target:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_target()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->target().data(), this->target().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "target");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ide.proto.Project.Variant)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ide.proto.Project.Variant)
  return false;
#undef DO_
}

void Project_Variant::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ide.proto.Project.Variant)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required string build_dir = 2;
  if (has_build_dir()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->build_dir().data(), this->build_dir().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "build_dir");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->build_dir(), output);
  }

  // optional string target = 3 [default = "all"];
  if (has_target()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->target().data(), this->target().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "target");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->target(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ide.proto.Project.Variant)
}

::google::protobuf::uint8* Project_Variant::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ide.proto.Project.Variant)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required string build_dir = 2;
  if (has_build_dir()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->build_dir().data(), this->build_dir().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "build_dir");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->build_dir(), target);
  }

  // optional string target = 3 [default = "all"];
  if (has_target()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->target().data(), this->target().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "target");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->target(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ide.proto.Project.Variant)
  return target;
}

int Project_Variant::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required string build_dir = 2;
    if (has_build_dir()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->build_dir());
    }

    // optional string target = 3 [default = "all"];
    if (has_target()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->target());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Project_Variant::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Project_Variant* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Project_Variant*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Project_Variant::MergeFrom(const Project_Variant& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_build_dir()) {
      set_build_dir(from.build_dir());
    }
    if (from.has_target()) {
      set_target(from.target());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Project_Variant::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Project_Variant::CopyFrom(const Project_Variant& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Project_Variant::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Project_Variant::Swap(Project_Variant* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(build_dir_, other->build_dir_);
    std::swap(target_, other->target_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Project_Variant::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Project_Variant_descriptor_;
  metadata.reflection = Project_Variant_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

::std::string* Project::_default_root_ = NULL;
#ifndef _MSC_VER
const int Project::kNameFieldNumber;
const int Project::kRootFieldNumber;
const int Project::kFileFieldNumber;
const int Project::kVariantFieldNumber;
#endif  // !_MSC_VER

Project::Project()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ide.proto.Project)
}

void Project::InitAsDefaultInstance() {
}

Project::Project(const Project& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ide.proto.Project)
}

void Project::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  root_ = const_cast< ::std::string*>(_default_root_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Project::~Project() {
  // @@protoc_insertion_point(destructor:ide.proto.Project)
  SharedDtor();
}

void Project::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (root_ != _default_root_) {
    delete root_;
  }
  if (this != default_instance_) {
  }
}

void Project::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Project::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Project_descriptor_;
}

const Project& Project::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_project_2fproject_2eproto();
  return *default_instance_;
}

Project* Project::default_instance_ = NULL;

Project* Project::New() const {
  return new Project;
}

void Project::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    if (has_root()) {
      if (root_ != _default_root_) {
        root_->assign(*_default_root_);
      }
    }
  }
  file_.Clear();
  variant_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Project::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ide.proto.Project)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_root;
        break;
      }

      // optional string root = 2 [default = "."];
      case 2: {
        if (tag == 18) {
         parse_root:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_root()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->root().data(), this->root().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "root");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_file;
        break;
      }

      // repeated string file = 3;
      case 3: {
        if (tag == 26) {
         parse_file:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_file()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->file(this->file_size() - 1).data(),
            this->file(this->file_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "file");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_file;
        if (input->ExpectTag(34)) goto parse_variant;
        break;
      }

      // repeated .ide.proto.Project.Variant variant = 4;
      case 4: {
        if (tag == 34) {
         parse_variant:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_variant()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_variant;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ide.proto.Project)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ide.proto.Project)
  return false;
#undef DO_
}

void Project::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ide.proto.Project)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional string root = 2 [default = "."];
  if (has_root()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->root().data(), this->root().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "root");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->root(), output);
  }

  // repeated string file = 3;
  for (int i = 0; i < this->file_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->file(i).data(), this->file(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "file");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->file(i), output);
  }

  // repeated .ide.proto.Project.Variant variant = 4;
  for (int i = 0; i < this->variant_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->variant(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ide.proto.Project)
}

::google::protobuf::uint8* Project::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ide.proto.Project)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string root = 2 [default = "."];
  if (has_root()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->root().data(), this->root().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "root");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->root(), target);
  }

  // repeated string file = 3;
  for (int i = 0; i < this->file_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file(i).data(), this->file(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "file");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->file(i), target);
  }

  // repeated .ide.proto.Project.Variant variant = 4;
  for (int i = 0; i < this->variant_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->variant(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ide.proto.Project)
  return target;
}

int Project::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string root = 2 [default = "."];
    if (has_root()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->root());
    }

  }
  // repeated string file = 3;
  total_size += 1 * this->file_size();
  for (int i = 0; i < this->file_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->file(i));
  }

  // repeated .ide.proto.Project.Variant variant = 4;
  total_size += 1 * this->variant_size();
  for (int i = 0; i < this->variant_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->variant(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Project::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Project* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Project*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Project::MergeFrom(const Project& from) {
  GOOGLE_CHECK_NE(&from, this);
  file_.MergeFrom(from.file_);
  variant_.MergeFrom(from.variant_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_root()) {
      set_root(from.root());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Project::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Project::CopyFrom(const Project& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Project::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->variant())) return false;
  return true;
}

void Project::Swap(Project* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(root_, other->root_);
    file_.Swap(&other->file_);
    variant_.Swap(&other->variant_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Project::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Project_descriptor_;
  metadata.reflection = Project_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace ide

// @@protoc_insertion_point(global_scope)
